window.BLUE_COAST_AUTH = Object.freeze({
  firebaseConfig: Object.freeze({
    apiKey: "AIzaSyDBqOWr2lorQhRqMBcSPWxon9z8Mzzyzds",
    authDomain: "blue-coast-hotel-gerg45.firebaseapp.com",
    projectId: "blue-coast-hotel-gerg45",
    storageBucket: "blue-coast-hotel-gerg45.firebasestorage.app",
    messagingSenderId: "729651484632",
    appId: "1:729651484632:web:e4bfdca173db16bbfdc4ad",
  }),
  accounts: Object.freeze({
    admin: Object.freeze({
      email: "admin@blue-coast-hotel-gerg45.firebaseapp.com",
      label: "Administración",
      role: "Administrador",
      defaultModule: "menu",
      allowedModules: Object.freeze([
        "menu",
        "reservas",
        "checkin",
        "bebidas",
        "checkout",
        "cajas",
        "registro",
        "inventario",
        "empleados",
      ]),
    }),
    recepcion: Object.freeze({
      email: "recepcion@blue-coast-hotel-gerg45.firebaseapp.com",
      label: "Recepción",
      role: "Reservas, ingresos y egresos",
      defaultModule: "reservas",
      allowedModules: Object.freeze(["reservas", "checkin", "checkout", "registro"]),
    }),
    mozo: Object.freeze({
      email: "mozo@blue-coast-hotel-gerg45.firebaseapp.com",
      label: "Mozo",
      role: "Estación de bebidas",
      defaultModule: "bebidas",
      allowedModules: Object.freeze(["bebidas"]),
    }),
    caja: Object.freeze({
      email: "caja@blue-coast-hotel-gerg45.firebaseapp.com",
      label: "Caja",
      role: "Bebidas y Stock e Inventario",
      defaultModule: "inventario",
      allowedModules: Object.freeze(["inventario", "bebidas"]),
    }),
  }),
});
